name: InvadedLandsEvents
authors: [nicbo, starzorrow]
version: 1.0
main: me.nicbo.InvadedLandsEvents.EventsMain
description: Remake of the invadedlands events
depend: [WorldGuard]

commands:
  event:
    usage: /<command>
    aliases: e
  eventconfig:
    usage: /<command>
    aliases: econfig
